# Generated by Django 4.2.3 on 2023-11-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fireapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspot",
            name="user_name",
        ),
    ]
