# Generated by Django 4.2.3 on 2023-11-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fireapp", "0002_remove_parkingspot_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspot",
            name="user_name",
            field=models.CharField(default=213, max_length=100),
            preserve_default=False,
        ),
    ]
