# Generated by Django 4.2.3 on 2023-11-01 17:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("fireapp", "0003_parkingspot_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingspot",
            old_name="isempty",
            new_name="is_available",
        ),
        migrations.RemoveField(
            model_name="parkingspot",
            name="name",
        ),
        migrations.RemoveField(
            model_name="parkingspot",
            name="occupied_duration",
        ),
        migrations.RemoveField(
            model_name="parkingspot",
            name="occupied_start_time",
        ),
        migrations.RemoveField(
            model_name="parkingspot",
            name="spotid",
        ),
        migrations.RemoveField(
            model_name="parkingspot",
            name="user_name",
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="parkingspot",
            name="spot_number",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parking_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fireapp.parkingspot",
                    ),
                ),
            ],
        ),
    ]
